
trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: Npm@1
  inputs:
    command: 'custom'    
    customCommand: 'install newman -g'

- task: Npm@1
  inputs:
    command: 'custom'    
    customCommand: 'npm install -g newman-reporter-htmlextra'

- task: CmdLine@2
  inputs:
    script: 'newman run collection.json -g globals.json -r htmlextra --reporter-htmlextra-export ./results/report.html'
  